### PR TITLE
Adding Django 1.7 support

### PR DESCRIPTION
**Pull request by victornovais**
Few considerations:

- Added Django 1.7.5 to Travis
- Making runtests support Django 1.7

PS: The warning messages when running tests with Django 1.7 are due to settings attribute 'MIDDLEWARE_CLASSES' that wasn't present. To avoid the warning I added that empty and everything worked.

### CODE REVIEW

**Comment by victornovais** [comment]
@chrisdev I tried to incluce Django 1.7 in Travis and an error ocurred. I'm not familiar with Travis and I don't know what went wrong but I realized that you have another PR seeing that, what should I do?

PS: Django 1.7 drops support for Python 2.6, so you probally will have to remove that in Travis if you are testing with Django 1.7.

**Comment by chrisdev** [comment]
@victornovais seeing the error triggered a recollection about the difference with standalone scripts under Django 1.7. 

http://django.readthedocs.org/en/latest/releases/1.7.html#standalone-scripts

Also travis is bit flakey.

**Comment by victornovais** [comment]
I had some problems with python 3 compatibility, but now everything is fine. I also added the django 1.7 in tox.

A reminder, as Django 1.7 does not support Python 2.6, only python > 2.7 builds will include this version of Django.

**Comment by chrisdev** [comment]
Nice job @victornovais and thanks for your contribution :dancer:

**Comment by victornovais** [comment]
@chrisdev, can you please launch this release? if possible, in Pypi... I'll be grateful.

**Comment by chrisdev** [comment]
@victornovais forgot to ping you did PyPI release early this morning

**Comment by victornovais** [comment]
Thank you so much

**Pull request merged**
