### PR TITLE
Improved coerce_float paramater

### PR DESCRIPTION
**Pull request by ZuluPro**
I:
- Added a compat for anontations
- coerce_float is now new in to_pivot_table and fixed in other methods.

### CODE REVIEW

**Comment by chrisdev** [comment]
@ZuluPro coverage has decreased. Did you include your tests in the PR?

**Comment by ZuluPro** [comment]
@chrisdev I didn't change the API behavior and lint code, just small improvements, so no need to write new tests.

About coverage, it seems to be a bug, it decreases on thing I didn't change;

**Comment by chrisdev** [comment]
Ok we don’t feel we need to write some even though this PR is reducing coverage by more that 5%. At least you can provide an example of the usage so I can include in the docs. We’ve got some users who are extremely conservative and we’re going to get some push back without an explanation

**Comment by ZuluPro** [comment]
Yes of course,

In facts, I created another Django app on top of your project: [django-pivot2](https://github.com/cloudspectatordevelopment/django-pivot2)

It's a toolbox to play with QuerySet/Pivot table. Actually I'm using the patch in this PR to make my app work.

But without the patch, I cannot use ``coerce_float`` directly from the method ``.to_pivot_table``.

Here's exactly where I'm using it:
https://github.com/cloudspectatordevelopment/django-pivot2/blob/master/django_pivot/forms.py#L65

**Comment by chrisdev** [comment]
Sorry @ZuluPro, now I understand 👍  I think we may have to tweak coverage /coveralls. I did not have my Laptop  with me yesterday (Christmas Vacation) but we'll try to sort things over the weekend for sure

**Comment by chrisdev** [comment]
@ZuluPro we're going to have to stop supporting all versions of Django before 1.8

**Comment by ZuluPro** [comment]
@chrisdev Ok, I can do another MR for that if you want ;)

**Pull request merged**
