### PR TITLE
Fix several deprecation warnings in pandas 2.1 which became actual errors in 2.2

### PR DESCRIPTION
**Pull request by bixbyr**
Fix for https://github.com/chrisdev/django-pandas/issues/156 in response to several minor pandas api changes. Tested with Django 4.2.9 and pandas 2.1.0.

### CODE REVIEW

**Comment by chrisdev** [comment]
Thanks @bixbyr some tests are failing. I  I think we can ignore the Python 2.7 but apparently the for newer versions the pandas the testing module has been deprecated so we need to do our own makeTimeDataFrame

**Comment by jayvdb** [comment]
ping @bixbyr , will you be able to do the extra work requested by @chrisdev to get the CI to pass?

**Comment by chrisdev** [comment]
@bixbyr sorry for taking so long to respond. Was down with COVID! I thought this thing had gone away but its still around  Still recovering so give me a few days.  
Yes I think we should just deprecate support for python 2. Although last time I tried to do so there was a bit of an uproar. But think this time it goes!

**Comment by bixbyr** [comment]
Any updates? Will this be approved and a new version released?

**Pull request merged**
