### PR TITLE
fixed typo in README.rst + Handle ValuesQuerySet

### PR DESCRIPTION
**Pull request by gtnx**

### CODE REVIEW

**Comment by chrisdev** [comment]
@gtnx think we need to remove the travis dependency for python 2.6 and the pull request should be good.
Not sure why I added it as Django 1.7 no longer supports it 2.6
Have we done any testing on Django 1.7?

**Comment by gtnx** [comment]
Why do you say that?
4 builds failed. 2 of them with python 2.7.
I don't understand why the build failed when i look  the details. I don't know much about Travis. Is it possible to launch another build?

**Comment by chrisdev** [comment]
Hmmm, you are correct of course.
I'm in a meeting now so i gave a cursory glance of the Travis log. Apologies I should pay more attention :)

But i've found that the  Travis service is a bit flakey so for example our Django 1.4 version is kind of outdated we so should really use Django 1.4.18 and sometimes travis builds fail because it can't download dependencies etc.

What I do is to  ensure that I have the recommended versions of django, pandas, numpy and  get it to work with tox.ini then edit the the .travis.yml.

You can then commit and push and travis will run again.

**Comment by gtnx** [comment]
Everything went well this time... Seems that Travis is not 100% reliable

**Comment by chrisdev** [comment]
@gtnx :dancer: 
Do we have any new tests for this new use case

**Comment by gtnx** [comment]
No indeed, i will do it tonight.
Btw, the last PR you merged has never been pushed to the pypi repository. Could you push a new version? Thanks!

**Comment by chrisdev** [comment]
Ok I'll do this a bit later today when I return to base

**Pull request merged**
